import { StyleSheet } from 'aphrodite';

export const styles = StyleSheet.create({
  list: {
    display: 'flex',
    flex: '0 0 320px',
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    maxHeight: 'calc(100vh - 100px)',
    borderRadius: '8px',
    marginRight: '22px',
    boxSizing: 'border-box',
    padding: '20px',
    boxShadow: '0px 10px 20px -13px rgba(32, 56, 117, 0.35)',
  },
  name: {
    fontSize: 20,
    lineHeight: 2,
    fontWeight: 500,
    letterSpacing: 1,
  },
  task: {
    boxSizing: 'border-box',
    padding: 15,
    borderRadius: 2,
    boxShadow: '0px 1px 7px 0px rgba(32, 56, 117, 0.35)',
    marginBottom: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  tasks: {
    // margin: '10px 0px',
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    overflowY: 'auto',
    boxSizing: 'border-box',
    padding: '5px 5px',
  },
  delete: {
    backgroundColor: '#FFFFFF',
    width: 30,
    height: 30,
    borderTopRightRadius: 8,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    marginLeft: 1,
    marginRight: 1,
    backgroundColor: '#000000',
  },
  addTask: {
    fontSize: 14,
    textAlign: 'center',
    cursor: 'pointer',
    color: '#b6babd',
    fontWeight: '500',
    marginTop: 14,
  },
  inputContainer: {
    marginBottom: 10,
  },
});
